# -*- coding: utf-8 -*-
"""northwind-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fPnne4U1TdNfz1kFxbkBtAnCxSuaMDwy
"""



# Northwind Database Analysis - Market insights from sales data

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt


plt.rcParams["figure.figsize"] = (12, 6)

# Connect to database
conn = sqlite3.connect("Northwind.db")

# Revenue by product category
query_cat = """
SELECT
    c.CategoryName,
    SUM(od.Quantity * p.Price) AS Revenue
FROM Categories AS c
JOIN Products AS p ON c.CategoryID = p.CategoryID
JOIN OrderDetails AS od ON p.ProductID = od.ProductID
GROUP BY c.CategoryName
ORDER BY Revenue DESC
"""
df_cat = pd.read_sql_query(query_cat, conn)


print("Revenue by category:\n", df_cat, "\n")

plt.bar(df_cat["CategoryName"], df_cat["Revenue"], color='steelblue')
plt.title("Revenue by Category", fontsize=14, fontweight='bold')
plt.ylabel("Revenue ($)")
plt.xlabel("Product Category")
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()


top_category = df_cat.iloc[0, 0]
print(f"Top category: {top_category}\n")

# Demand over time for the top category
query_demand = """
SELECT
    strftime('%Y-%m', o.OrderDate) AS Month,
    SUM(od.Quantity) AS TotalQuantity
FROM Orders AS o
JOIN OrderDetails AS od ON o.OrderID = od.OrderID
JOIN Products AS p ON od.ProductID = p.ProductID
JOIN Categories AS c ON p.CategoryID = c.CategoryID
WHERE c.CategoryName = ?
GROUP BY Month
ORDER BY Month
"""
df_demand = pd.read_sql_query(query_demand, conn, params=(top_category,))
df_demand["Month"] = pd.to_datetime(df_demand["Month"])

print(f"Demand over time for category '{top_category}':\n", df_demand)
print(f"Note: February 1997 only contains data through the 12th day.\n")

plt.plot(df_demand["Month"], df_demand["TotalQuantity"], marker="o", color="steelblue", linewidth=2)
plt.title(f"Monthly Demand - {top_category}", fontsize=14, fontweight='bold')
plt.xlabel("Month")
plt.ylabel("Quantity Sold (units)")
plt.ylim(0, df_demand["TotalQuantity"].max() * 1.1)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Revenue by country
query_country = """
SELECT
    c.Country,
    SUM(od.Quantity * p.Price) AS Revenue
FROM Customers AS c
JOIN Orders AS o ON c.CustomerID = o.CustomerID
JOIN OrderDetails AS od ON o.OrderID = od.OrderID
JOIN Products AS p ON od.ProductID = p.ProductID
GROUP BY c.Country
ORDER BY Revenue DESC
LIMIT 10
"""
df_country = pd.read_sql_query(query_country, conn)
df_country.index = range(1, len(df_country) + 1)

print("Revenue by country (Top 10):\n", df_country, "\n")


plt.barh(df_country["Country"][::-1], df_country["Revenue"][::-1], color='steelblue')
plt.title("Revenue by Country (Top 10)", fontsize=14, fontweight='bold')
plt.xlabel("Revenue ($)")
plt.ylabel("Country")
plt.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.show()

# Top performing employee
query_best_employee = """
SELECT
    e.FirstName || ' ' || e.LastName AS EmployeeName,
    SUM(od.Quantity * p.Price) AS Revenue
FROM Employees AS e
JOIN Orders AS o ON e.EmployeeID = o.EmployeeID
JOIN OrderDetails AS od ON o.OrderID = od.OrderID
JOIN Products AS p ON od.ProductID = p.ProductID
GROUP BY e.EmployeeID
ORDER BY Revenue DESC
LIMIT 1
"""
best_employee = pd.read_sql_query(query_best_employee, conn)
name = best_employee["EmployeeName"].iloc[0]
rev = best_employee["Revenue"].iloc[0]

print(f"Top performing employee: {name} with total sales of ${rev:,.2f}\n")

# Close database connection
conn.close()